CPB-214(feat): add supervisor ui to cp-stack

diff --git a/tools/cp-stack/bin/start-server b/tools/cp-stack/bin/start-server
--- a/tools/cp-stack/bin/start-server
+++ b/tools/cp-stack/bin/start-server
@@ -10,6 +10,7 @@ script_dir="$(pwd)"
 . "$script_dir"/utils/resolve_secrets.sh
 
 local_ui=0
+local_sui=0
 local_api=0
 
 while [ "$1" != "" ];
@@ -17,6 +18,9 @@ do
    case $1 in
     --local-ui)
       local_ui=1
+      ;;
+    --local-sui)
+      local_sui=1
       ;;
     --local-api)
       local_api=1
@@ -39,6 +43,12 @@ resolve_secrets "$script_dir/../.env.ui.template" \
                 "hmpps-community-payback-dev" \
                 "${ui_secret_names[@]}"
 
+sui_secret_names=("hmpps-community-payback-supervisors-ui-auth-code" "hmpps-community-payback-supervisors-ui-client-creds" "hmpps-community-payback-supervisors-ui-session-secret")
+resolve_secrets "$script_dir/../.env.sui.template" \
+                "$script_dir/../.env.sui" \
+                "hmpps-community-payback-dev" \
+                "${sui_secret_names[@]}"
+
 tiltArgs=""
 
 if [ $local_api -gt 0 ]; then
@@ -56,9 +66,20 @@ if [ $local_ui -gt 0 ]; then
     exit 1
   fi
 
-  touch ${LOCAL_CP_UI_PATH}/.env
+  touch "${LOCAL_CP_UI_PATH}"/.env
 
   tiltArgs="$tiltArgs --local-ui"
+fi
+
+if [ $local_sui -gt 0 ]; then
+  if [ -z "${LOCAL_CP_SUI_PATH}" ]; then
+    echo "Path to local Supervisor UI not found, please ensure you have set the LOCAL_CP_SUI_PATH environment variable and try again"
+    exit 1
+  fi
+
+  touch "${LOCAL_CP_SUI_PATH}"/.env
+
+  tiltArgs="$tiltArgs --local-sui"
 fi
 
 echo "==> Starting Tilt"
